Repository Heutlett/Proyecto_2_CE, pull requests merged in 2019-10, with the labels that each got.

#9 Se agrega el borrado al manejo de archivos de la biblioteca
  prueba.txt
  src/com/textfinder/documentlibrary/DocumentLibrary.java
  src/com/textfinder/documentlibrary/documents/prueba1.pdf
  src/com/textfinder/documentlibrary/documents/prueba2.pdf
  src/com/textfinder/documentlibrary/documents/prueba3.pdf
  src/com/textfinder/view/Ventana.java
Labels: Historia de usuario (1), Historia de usuario (6)

#10 Se agrega parcialmente la funcion de refrescar los archivos
  src/com/textfinder/documentlibrary/DocumentLibrary.java
  src/com/textfinder/documentlibrary/documents/prueba1.pdf
  src/com/textfinder/documentlibrary/documents/prueba2.pdf
  src/com/textfinder/documentlibrary/documents/prueba3.pdf
  src/com/textfinder/documentlibrary/documents/pruebaPDF.pdf
  src/com/textfinder/view/Window.java
Labels: Estructuras, Historia de usuario (1)

#13 Se agrega el indexing de archivos PDF
  Proyecto_2_CE.iml
  src/com/textfinder/documentlibrary/DocumentLibrary.java
  src/com/textfinder/documentlibrary/LeerPdf.java
  src/com/textfinder/documentlibrary/documents/prueba.pdf
  src/com/textfinder/documentlibrary/documents/prueba4.pdf
  src/com/textfinder/structures/BinarySearchTree.java
  src/com/textfinder/structures/Indexing.java
  src/com/textfinder/structures/Occurrence.java
  src/com/textfinder/structures/PDFManager.java
  src/com/textfinder/view/Window.java
Labels: Estructuras, Historia de usuario (2)

#14 Se agrega la libreria del parsing de DOCX y se implementa su indexing
  Proyecto_2_CE.iml
  src/com/textfinder/documentlibrary/documents/pruebaword.docx
  src/com/textfinder/filemanagers/DOCXManager.java
  src/com/textfinder/filemanagers/PDFManager.java
  src/com/textfinder/filemanagers/TXTManager.java
  src/com/textfinder/libs/poi-4.1.0/lib/activation-1.1.1.jar
  src/com/textfinder/libs/poi-4.1.0/lib/commons-codec-1.12.jar
  src/com/textfinder/libs/poi-4.1.0/lib/commons-collections4-4.3.jar
  src/com/textfinder/libs/poi-4.1.0/lib/commons-compress-1.18.jar
  src/com/textfinder/libs/poi-4.1.0/lib/commons-logging-1.2.jar
  src/com/textfinder/libs/poi-4.1.0/lib/commons-math3-3.6.1.jar
  src/com/textfinder/libs/poi-4.1.0/lib/jaxb-api-2.3.0.jar
  src/com/textfinder/libs/poi-4.1.0/lib/jaxb-core-2.3.0.1.jar
  src/com/textfinder/libs/poi-4.1.0/lib/jaxb-impl-2.3.0.1.jar
  src/com/textfinder/libs/poi-4.1.0/lib/junit-4.12.jar
  src/com/textfinder/libs/poi-4.1.0/lib/log4j-1.2.17.jar
  src/com/textfinder/libs/poi-4.1.0/ooxml-lib/curvesapi-1.06.jar
  src/com/textfinder/libs/poi-4.1.0/ooxml-lib/xmlbeans-3.1.0.jar
  src/com/textfinder/libs/poi-4.1.0/poi-4.1.0.jar
  src/com/textfinder/libs/poi-4.1.0/poi-examples-4.1.0.jar
  src/com/textfinder/libs/poi-4.1.0/poi-excelant-4.1.0.jar
  src/com/textfinder/libs/poi-4.1.0/poi-ooxml-4.1.0.jar
  src/com/textfinder/libs/poi-4.1.0/poi-scratchpad-4.1.0.jar
  src/com/textfinder/structures/Indexing.java
  src/com/textfinder/structures/KeyNode.java
  src/com/textfinder/structures/PDFManager.java
  src/com/textfinder/view/Window.java
Labels: Estructuras, Historia de usuario (2)

#17 Se soluciona un bug cuando se muestra un documento en vista previa
  src/com/textfinder/filemanagers/DOCXManager.java
  src/com/textfinder/filemanagers/PDFManager.java
  src/com/textfinder/structures/Indexing.java
Labels: bug

#18 Se agrega la base de los ordenamientos
  src/com/textfinder/documentlibrary/documents/nueva.txt
  src/com/textfinder/structures/Indexing.java
  src/com/textfinder/view/Window.java
Labels: Estructuras, Historia de usuario (3)

#19 Se empieza la base de resaltar los resultados
  src/com/textfinder/structures/Indexing.java
  src/com/textfinder/view/Window.java
Labels: Estructuras, Historia de usuario (4)

#20 Se unifican las ocurrencias de la misma palabra en el mismo documento
  src/com/textfinder/documentlibrary/documents/pruebaTXT.txt
  src/com/textfinder/structures/BinarySearchTree.java
  src/com/textfinder/structures/Indexing.java
  src/com/textfinder/structures/Occurrence.java
  src/com/textfinder/structures/Position.java
Labels: Estructuras, Historia de usuario (2), bug

#21 Se agrega el resaltado de palabras individuales
  src/com/textfinder/structures/BinarySearchTree.java
  src/com/textfinder/structures/Indexing.java
  src/com/textfinder/view/Window.java
Labels: Estructuras, GUI, Historia de usuario (4)

#22 Se da un formato nuevo al subrayado
  src/com/textfinder/structures/Indexing.java
Labels: GUI, Historia de usuario (4)

#27 Se actualiza el metodo de busqueda con el indexing
  src/com/textfinder/structures/Indexing.java
Labels: Estructuras, Historia de usuario (4)

#29 Se agrega el buscado por frase
  src/com/textfinder/documentlibrary/documents/Clase 1 Semana 10.docx
  src/com/textfinder/documentlibrary/documents/Clase 1 Semana 6.docx
  src/com/textfinder/documentlibrary/documents/Clase 2 Semana 1.docx
  src/com/textfinder/structures/Indexing.java
  src/com/textfinder/view/Window.java
Labels: Estructuras, Historia de usuario (4)
